# Generated by Django 4.1.5 on 2023-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="public_responses",
            field=models.BooleanField(default=False),
        ),
    ]
