# Generated by Django 4.1.5 on 2023-02-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_public_responses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="public_responses",
        ),
    ]
